### ISSUE TITLE
`Face` has been removed from ThreeJS in R125

### ISSUE THREAD

**Issue by donalffons** [donalffons/opencascade.js-examples#20]
See [this post](https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401).

The `openCascadeHelper.js` would need to refactored to account for this, so that upgrading to recent ThreeJS versions becomes possible again.

Alternatively, we could eliminate `openCascadeHelper.js` alltogether and instead utilize OpenCascade's `RWGltf_CafWriter` to export a GLB file, which could then be loaded without having to worry about low-level tessellation extraction code.

It might be good to have example code for both approaches, though.

**Comment by promontis** [comment]
Cool... just bumped into this myself. Going to try it out in the next couple of weeks

**Comment by donalffons** [comment]
Check out the example code that I posted [here](https://github.com/donalffons/opencascade.js/discussions/89#discussioncomment-1374536) (You can probably take out the `BinXCAF` - related lines, if you're not planning to export `.xbf` files).

**Comment by donalffons** [comment]
This is not necessary any longer, as shown on the [new homepage](https://ocjs.org/docs/getting-started/hello-world).
