### ISSUE TITLE
why using "async" before openCascade

### ISSUE THREAD

**Issue by iamnotstone** [donalffons/opencascade.js-examples#21]
Hello! In all of those examples, I found an "async" keywords before some functions like below:

```javascript

async openCascade => {...}

```

So. Why are you doing this? To make sure the return value is a Promise ?

**Comment by donalffons** [comment]
You're right. Using `async` is not really necessary for most of the functions (except for `loadSTEPorIGES` as it's awaiting `loadFileAsync`). I removed those unnecessary async keywords in the beta branch.
