### ISSUE TITLE
the memory issues

### ISSUE THREAD

**Issue by iamnotstone** [donalffons/opencascade.js-examples#8]
1. From my system monitor, I find the memory usage by the browser will keep increasing everytime after I refresh the page when running the '_bottle example_' .
2. The tesselate function doesn't release memory. for example, adding the code below to a bottle example:
```
  let i = 0
  while(i < 10000){
    scene.remove(scene.getObjectByName("shape"));
    await addShapeToScene(openCascade, bottle, scene);
    i ++
    console.log('i=', i)
  }

```
On my compute, after added those code, the memory usage will keep increasing in both of the bottle example. And the page will throw a error when the values of the i is around 1440.

**Comment by iamnotstone** [comment]
The main problem is the new constructed points never deconstruced. Try this code below, and you'll see the problem:
```
import { initOpenCascade } from "opencascade.js";                                            

function createPoint(openCascade){             
  for(let i = 0; i < 10000; i ++){
    var p = new openCascade.gp_Pnt_3(1,1,1)
  }
} 
  
    
initOpenCascade().then(oc => oc.ready).then(async openCascade => {                                      
  for(let i = 0; i < 10000; i ++){                                                                      
    createPoint(openCascade)
    console.log('10000 points created:', i)                                                             
  } 
}); 
```

**Comment by iamnotstone** [comment]
I found a solution for this. I have to call the delete function for every created object. like this:
import { initOpenCascade } from "opencascade.js";                                            
```
function createPoint(openCascade){             
  for(let i = 0; i < 10000; i ++){
    var p = new openCascade.gp_Pnt_3(1,1,1)
    p.delete()
  }
} 
  
    
initOpenCascade().then(oc => oc.ready).then(async openCascade => {                                      
  for(let i = 0; i < 10000; i ++){                                                                      
    createPoint(openCascade)
    console.log('10000 points created:', i)                                                             
  } 
}); 
```

**Comment by donalffons** [comment]
Yeah, fixing the memory management in the examples is somewhere on my to-do list.

Generally speaking, there is no out-of-the-box automatic memory management in C++ and therefore there is none in OpenCascade.js. If you allocate any OpenCascade.js class with `= new openCascade.anything()`, you will have to call the `.delete()` method later. I haven't done any benchmarking or extensive testing myself, but I think this should already work fine in the library.

As of today, I think [manual memory management](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-management) is the way to go...
Theoretically, an alternative could be to generate [bindings for smart pointers](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#smart-pointers). I believe those C++ smart pointers do automatic reference counting and automatically delete an underlying object if there are no references to it any more. However, it seems like smart pointers are not used in OpenCascade and therefore I don't think this will actually help.

**Comment by iamnotstone** [comment]
But the problem is we have to also call the delete function for every object been generated when calculating. In the visualize.js, I have to call the delete function for every gp_Pnt object been generated by this line:
```
 const Nodes = myT.get().Nodes();
```
And even been generated by:
```
const p = Nodes.Value(i).Transformed(aLocation.Transformation());
```
 to call delete function for the middle value, I have to rewrite this line to
```
const p = Nodes.Value(i)
const p1 = p.Transformed(aLocation.Transformation())
...
p.delete()
p1.delete()

```

**Comment by donalffons** [comment]
There might be a way of handling memory management without having to manually free up memory for every object created: https://github.com/donalffons/opencascade.js/discussions/79

I would suggest not to pollute the examples with memory management code, as this makes it much harder to understand them.

**Comment by iamnotstone** [comment]
It's really good news for this project !!!
